version: "3"

networks: 
  dev-network:
    driver: bridge

services:
  app:
    container_name: app
    restart: always
    build: ./admin-panel
    networks:
      - dev-network
    ports:
      - "3000:3000"
    privileged:  true
    volumes:
      - './admin-panel:/app'
      - 'app-node_modules:/app/node_modules'
    links:
      - api
  api:
    container_name: api
    restart: always
    build: ./server
    networks:
      - dev-network
    ports:
      - "8888:8888"
    privileged:  true
    volumes:
      - './server:/api'
      - 'api-node_modules:/api/node_modules'
    links:
      - mongo
  nginx:
    build: ./nginx
    links:
      - api
      - app
    depends_on:
      - api
      - app
    ports:
      - "8080:80"
    networks:
      - dev-network
  mongo:
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=challenge
      - MONGO_INITDB_ROOT_PASSWORD=Mv534r73
      - MONGO_INITDB_DATABASE=challenge
    image: mongo:latest
    command: mongod --auth
    networks:
      - dev-network
    ports:
      - "27017:27017"
      
volumes:
  api-node_modules:
  app-node_modules:    